/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Image;
import java.awt.MenuComponent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import pojo.Equipo;
import pojo.Grafica;
import pojo.Jugador;
import pojo.Sound;
import pojo.Torneo;
import service.EquipoServiceImpl;
import service.IEquipoService;
import service.IJugadorService;
import service.ITorneoService;
import service.JugadorServiceImpl;
import service.TorneoServiceImpl;
import service.validacionService;

/**
 *
 * @author labdessw04
 */
public class DatosGeneral extends javax.swing.JFrame {

    private int xMouse, yMouse;
    private Torneo torneo;
    private ITorneoService torneoService;
    private IEquipoService equipoService;
    private DefaultTableModel modelTabla;
    private IJugadorService jugadorService;
    private String idEquipo = "";
    private String idJugador;
    private boolean continuar;

    public DatosGeneral(Torneo torneo) {

        this.torneo = torneo;
        initComponents();

        modelTabla = (DefaultTableModel) tablaEquipos.getModel();
        torneoService = new TorneoServiceImpl();
        equipoService = new EquipoServiceImpl();
        jugadorService = new JugadorServiceImpl();
        txtNombreTorneo1.setText(torneo.getNombreTorneo());
        txtCategoria1.setText(torneo.getCategoria());
        btnAgregarJugador.setVisible(false);

    }

    public DatosGeneral() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnExit = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        btnInicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnDatosTorneo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnDatosEquipo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnDatosJugadores = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnTablaEncuentro = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        backgroundViewPrincipal = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        background6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtNombreTorneo1 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        txtCategoria1 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        background3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEquipos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        background4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaJugadores = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaEquipos1 = new javax.swing.JTable();
        btnAgregarJugador = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel10 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        btnContinuar = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        txtNumeroJugador = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        txtTelefonoJugador = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtDireccionJugador = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtNombreJugador = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        txtNombreEquipo = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        btnContinuar1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtLogo = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(48, 76, 134));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 0, 51));
        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 51, 51));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/remove.png"))); // NOI18N
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btnExitMouseDragged(evt);
            }
        });
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 764, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 40));

        jPanel2.setBackground(new java.awt.Color(48, 76, 134));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setBackground(new java.awt.Color(255, 255, 255));
        logo.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        logo.setForeground(new java.awt.Color(255, 255, 255));
        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iLogo.png"))); // NOI18N
        logo.setText("Torneos");
        jPanel2.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 14, 160, -1));

        btnInicio.setBackground(new java.awt.Color(48, 76, 134));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        jLabel1.setText("Inicio");
        jLabel1.setToolTipText("");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setMaximumSize(new java.awt.Dimension(30, 20));
        jLabel1.setMinimumSize(new java.awt.Dimension(30, 20));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnInicioLayout = new javax.swing.GroupLayout(btnInicio);
        btnInicio.setLayout(btnInicioLayout);
        btnInicioLayout.setHorizontalGroup(
            btnInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );
        btnInicioLayout.setVerticalGroup(
            btnInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnInicioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 160, 30));

        btnDatosTorneo.setBackground(new java.awt.Color(48, 76, 134));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trophy.png"))); // NOI18N
        jLabel3.setText("Datos del torneo");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnDatosTorneoLayout = new javax.swing.GroupLayout(btnDatosTorneo);
        btnDatosTorneo.setLayout(btnDatosTorneoLayout);
        btnDatosTorneoLayout.setHorizontalGroup(
            btnDatosTorneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDatosTorneoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );
        btnDatosTorneoLayout.setVerticalGroup(
            btnDatosTorneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDatosTorneoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(btnDatosTorneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 160, 30));

        btnDatosEquipo.setBackground(new java.awt.Color(48, 76, 134));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/team.png"))); // NOI18N
        jLabel4.setText("Datos de equipos");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnDatosEquipoLayout = new javax.swing.GroupLayout(btnDatosEquipo);
        btnDatosEquipo.setLayout(btnDatosEquipoLayout);
        btnDatosEquipoLayout.setHorizontalGroup(
            btnDatosEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDatosEquipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );
        btnDatosEquipoLayout.setVerticalGroup(
            btnDatosEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDatosEquipoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(btnDatosEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 160, 30));

        btnDatosJugadores.setBackground(new java.awt.Color(48, 76, 134));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/player.png"))); // NOI18N
        jLabel6.setText("Datos de jugadores");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnDatosJugadoresLayout = new javax.swing.GroupLayout(btnDatosJugadores);
        btnDatosJugadores.setLayout(btnDatosJugadoresLayout);
        btnDatosJugadoresLayout.setHorizontalGroup(
            btnDatosJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDatosJugadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );
        btnDatosJugadoresLayout.setVerticalGroup(
            btnDatosJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDatosJugadoresLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(btnDatosJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 160, 30));

        btnTablaEncuentro.setBackground(new java.awt.Color(48, 76, 134));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vs.png"))); // NOI18N
        jLabel5.setText("Tabla de encuentros");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnTablaEncuentroLayout = new javax.swing.GroupLayout(btnTablaEncuentro);
        btnTablaEncuentro.setLayout(btnTablaEncuentroLayout);
        btnTablaEncuentroLayout.setHorizontalGroup(
            btnTablaEncuentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTablaEncuentroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );
        btnTablaEncuentroLayout.setVerticalGroup(
            btnTablaEncuentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnTablaEncuentroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(btnTablaEncuentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 160, 30));

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 170, 610));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Roboto Black", 1, 25)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Gestione su torneo con la opciones de lado izquierdo");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 660, 110));

        backgroundViewPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backgroundViewPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/playerLogo2.png"))); // NOI18N
        jPanel3.add(backgroundViewPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 610));

        jTabbedPane1.addTab("tab1", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        background6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("NOMBRE");

        txtNombreTorneo1.setEditable(false);
        txtNombreTorneo1.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreTorneo1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombreTorneo1.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreTorneo1.setText("Ingrese el nombre del torneo");
        txtNombreTorneo1.setBorder(null);
        txtNombreTorneo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreTorneo1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreTorneo1MousePressed(evt);
            }
        });
        txtNombreTorneo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreTorneo1ActionPerformed(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(153, 153, 153));

        jLabel13.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("CATEGORIA");

        txtCategoria1.setEditable(false);
        txtCategoria1.setBackground(new java.awt.Color(255, 255, 255));
        txtCategoria1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCategoria1.setForeground(new java.awt.Color(153, 153, 153));
        txtCategoria1.setText("Ingrese la categoria");
        txtCategoria1.setBorder(null);
        txtCategoria1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCategoria1MousePressed(evt);
            }
        });
        txtCategoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoria1ActionPerformed(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(153, 153, 153));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iLogo.png"))); // NOI18N
        jLabel14.setText("TORNEOS");

        javax.swing.GroupLayout background6Layout = new javax.swing.GroupLayout(background6);
        background6.setLayout(background6Layout);
        background6Layout.setHorizontalGroup(
            background6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background6Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(background6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(background6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(background6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(background6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(txtNombreTorneo1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 232, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(35, 35, 35))
        );
        background6Layout.setVerticalGroup(
            background6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background6Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel12)
                .addGap(26, 26, 26)
                .addComponent(txtNombreTorneo1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel14)
                .addGap(57, 57, 57)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(txtCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(background6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(background6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("tab2", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        background3.setBackground(new java.awt.Color(255, 255, 255));
        background3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaEquipos.setBackground(new java.awt.Color(65, 168, 224));
        tablaEquipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaEquipos);

        background3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 167, 660, 440));

        jButton1.setBackground(new java.awt.Color(65, 168, 224));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        background3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 20, -1, -1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(background3, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        background4.setBackground(new java.awt.Color(255, 255, 255));
        background4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaJugadores.setBackground(new java.awt.Color(65, 168, 224));
        tablaJugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "nombre", "direccion", "telefono", "numero", "equipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaJugadores.setMinimumSize(new java.awt.Dimension(450, 80));
        jScrollPane2.setViewportView(tablaJugadores);

        background4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 660, 360));

        tablaEquipos1.setBackground(new java.awt.Color(65, 168, 224));
        tablaEquipos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaEquipos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEquipos1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaEquipos1);

        background4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 660, 140));

        btnAgregarJugador.setBackground(new java.awt.Color(65, 168, 224));
        btnAgregarJugador.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarJugador.setText("agregar");
        btnAgregarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarJugadorActionPerformed(evt);
            }
        });
        background4.add(btnAgregarJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Seleccione un equipo para poder agregar jugadores");
        background4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 660, -1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(background4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.GridLayout(0, 3, 0, 2));
        jScrollPane4.setViewportView(jPanel10);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab5", jPanel7);

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnContinuar.setBackground(new java.awt.Color(65, 168, 224));
        btnContinuar.setForeground(new java.awt.Color(0, 0, 0));
        btnContinuar.setText("continuar");
        btnContinuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        jPanel8.add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, 30));

        jSeparator7.setForeground(new java.awt.Color(153, 153, 153));
        jPanel8.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 280, 10));

        txtNumeroJugador.setBackground(new java.awt.Color(255, 255, 255));
        txtNumeroJugador.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNumeroJugador.setForeground(new java.awt.Color(153, 153, 153));
        txtNumeroJugador.setText("Ingrese el número con el que jugará");
        txtNumeroJugador.setBorder(null);
        txtNumeroJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNumeroJugadorMousePressed(evt);
            }
        });
        txtNumeroJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroJugadorActionPerformed(evt);
            }
        });
        jPanel8.add(txtNumeroJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 280, 30));

        jLabel8.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("NUMERO DE JUGADOR");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jSeparator8.setForeground(new java.awt.Color(153, 153, 153));
        jPanel8.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 280, 10));

        txtTelefonoJugador.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefonoJugador.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtTelefonoJugador.setForeground(new java.awt.Color(153, 153, 153));
        txtTelefonoJugador.setText("Ingrese el teléfono del jugador");
        txtTelefonoJugador.setBorder(null);
        txtTelefonoJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefonoJugadorMousePressed(evt);
            }
        });
        txtTelefonoJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoJugadorActionPerformed(evt);
            }
        });
        jPanel8.add(txtTelefonoJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 280, 30));

        jLabel9.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("TELÉFONO");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, 30));

        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));
        jPanel8.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 280, 10));

        txtDireccionJugador.setBackground(new java.awt.Color(255, 255, 255));
        txtDireccionJugador.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtDireccionJugador.setForeground(new java.awt.Color(153, 153, 153));
        txtDireccionJugador.setText("Ingrese la dirección del jugador");
        txtDireccionJugador.setBorder(null);
        txtDireccionJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDireccionJugadorMousePressed(evt);
            }
        });
        txtDireccionJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionJugadorActionPerformed(evt);
            }
        });
        jPanel8.add(txtDireccionJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 280, 30));

        jLabel17.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("DIRECCIÓN");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel8.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 280, 10));

        txtNombreJugador.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreJugador.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombreJugador.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreJugador.setText("Ingrese el nombre del jugador");
        txtNombreJugador.setBorder(null);
        txtNombreJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreJugadorMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreJugadorMousePressed(evt);
            }
        });
        txtNombreJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreJugadorActionPerformed(evt);
            }
        });
        jPanel8.add(txtNombreJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 280, 30));

        jLabel18.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("NOMBRE");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/teamLogo.png"))); // NOI18N
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 350, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/undo (2).png"))); // NOI18N
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));

        jTabbedPane1.addTab("tab6", jPanel8);

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(0, 0, 0));
        lblLogo.setText("LOGO DEL EQUIPO");
        jPanel9.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        txtNombreEquipo.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreEquipo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombreEquipo.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreEquipo.setText("Ingrese el nombre del equipo");
        txtNombreEquipo.setBorder(null);
        txtNombreEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreEquipoMousePressed(evt);
            }
        });
        jPanel9.add(txtNombreEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 280, 30));

        jSeparator6.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel9.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 280, 10));

        btnContinuar1.setBackground(new java.awt.Color(65, 168, 224));
        btnContinuar1.setForeground(new java.awt.Color(0, 0, 0));
        btnContinuar1.setText("continuar");
        btnContinuar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContinuar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuar1ActionPerformed(evt);
            }
        });
        jPanel9.add(btnContinuar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, 30));

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/teamLogo.png"))); // NOI18N
        jPanel9.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 350, -1));

        jLabel20.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("NOMBRE");
        jPanel9.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        txtLogo.setBackground(new java.awt.Color(255, 255, 255));
        txtLogo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtLogo.setForeground(new java.awt.Color(153, 153, 153));
        txtLogo.setText("Click aqui para cargar su logo");
        txtLogo.setBorder(null);
        txtLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLogoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtLogoMousePressed(evt);
            }
        });
        txtLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLogoActionPerformed(evt);
            }
        });
        jPanel9.add(txtLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 280, 30));

        jSeparator9.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel9.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 280, 10));
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 70, 70));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ingrese los datos de su equipo");
        jPanel9.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 660, -1));

        jLabel21.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Click aqui para cargar una imagen generica.");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 290, 30));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/undo (2).png"))); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jPanel9.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));

        jTabbedPane1.addTab("tab7", jPanel9);

        background.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 660, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

        modelTabla = (DefaultTableModel) tablaEquipos.getModel();
        equipoService.mostrarEquipos(torneo.getEquipos(), modelTabla);

        jTabbedPane1.setSelectedIndex(2);


    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

        int a = torneo.getEquipos().size();
        if (a >= 2) {
            torneoService.Grafica(torneo, jPanel10);
        }
        jPanel10.updateUI();
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked

        System.exit(0);

    }//GEN-LAST:event_btnExitMouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed

        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered

    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseDragged

    }//GEN-LAST:event_btnExitMouseDragged

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        Sound.mousePass();
        btnDatosTorneo.setBackground(new Color(65, 168, 224));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        Sound.mousePass();
        btnInicio.setBackground(new Color(65, 168, 224));

    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        btnInicio.setBackground(new Color(48, 76, 134));
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        btnDatosTorneo.setBackground(new Color(48, 76, 134));
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        Sound.mousePass();
        btnDatosEquipo.setBackground(new Color(65, 168, 224));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        btnDatosEquipo.setBackground(new Color(48, 76, 134));
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        Sound.mousePass();
        btnDatosJugadores.setBackground(new Color(65, 168, 224));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        btnDatosJugadores.setBackground(new Color(48, 76, 134));
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        Sound.mousePass();
        btnTablaEncuentro.setBackground(new Color(65, 168, 224));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        btnTablaEncuentro.setBackground(new Color(48, 76, 134));
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txtCategoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoria1ActionPerformed

    private void txtCategoria1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCategoria1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoria1MousePressed

    private void txtNombreTorneo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreTorneo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreTorneo1ActionPerformed

    private void txtNombreTorneo1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreTorneo1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreTorneo1MousePressed

    private void txtNombreTorneo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreTorneo1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreTorneo1MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (torneo.getEquipos().size() < TorneoServiceImpl.maxEquipos) {
            jTabbedPane1.setSelectedIndex(6);
            jLabel10.removeAll();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "numero máximo de equipos alcanzado");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        modelTabla = (DefaultTableModel) tablaEquipos1.getModel();
        equipoService.mostrarEquipos(torneo.getEquipos(), modelTabla);

        modelTabla = (DefaultTableModel) tablaJugadores.getModel();
        if (!idEquipo.isEmpty()) {
            jugadorService.mostrarJugadores(torneo.getEquipos().get(idEquipo).getJugadores(), modelTabla, idEquipo);
        }

        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void btnAgregarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarJugadorActionPerformed
        jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_btnAgregarJugadorActionPerformed

    private void tablaEquipos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEquipos1MouseClicked
        idEquipo = tablaEquipos1.getValueAt(tablaEquipos1.getSelectedRow(), 0).toString();

        if (!idEquipo.isEmpty()) {
            btnAgregarJugador.setVisible(true);
            modelTabla = (DefaultTableModel) tablaJugadores.getModel();
            jugadorService.mostrarJugadores(torneo.getEquipos().get(idEquipo).getJugadores(), modelTabla, idEquipo);

        }
    }//GEN-LAST:event_tablaEquipos1MouseClicked

    private void txtNombreEquipoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreEquipoMousePressed

        if (txtNombreEquipo.getText().equals("Ingrese el nombre del equipo")) {

            txtNombreEquipo.setText("");
            txtNombreEquipo.setForeground(Color.black);

        }

    }//GEN-LAST:event_txtNombreEquipoMousePressed

    private void btnContinuar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuar1ActionPerformed
        continuar = false;

        if (!txtNombreEquipo.getText().equals("Ingrese el nombre del equipo") && !txtNombreEquipo.getText().isEmpty() && !txtLogo.getText().equals("Click aqui para cargar su logo")) {
            torneo.setEquipos(equipoService.crearEquipo(txtNombreEquipo.getText(), String.valueOf(torneo.getEquipos().size() + 1), txtLogo.getText()));
            continuar = true;
        } else {
            Sound.error();
            javax.swing.JOptionPane.showMessageDialog(this, "ingrese un nombre");
        }

        if (continuar) {
            Sound.sucessfull();

            //restablece los valores por defecto de los campos
            txtNombreEquipo.setText("Ingrese el nombre del equipo");
            txtNombreEquipo.setForeground(Color.gray);
            txtLogo.setText("Click aqui para cargar su logo");
            txtNombreEquipo.setForeground(Color.gray);
            jLabel10.setIcon(null);
            jLabel10.updateUI();
            jTabbedPane1.setSelectedIndex(2);
            equipoService.mostrarEquipos(torneo.getEquipos(), modelTabla);
        }
    }//GEN-LAST:event_btnContinuar1ActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        if (!txtNombreJugador.getText().equals("Ingrese el nombre del jugador") && !txtTelefonoJugador.getText().equals("Ingrese el teléfono del jugador") && !txtDireccionJugador.getText().equals("Ingrese la dirección del jugador") && !txtNumeroJugador.getText().equals("Ingrese el número con el que jugará") && !txtNumeroJugador.getText().isEmpty() && validacionService.isNumeric(txtNumeroJugador.getText()) && validacionService.isNumeric(txtTelefonoJugador.getText())) {
            Sound.sucessfull();
            String idJugador = String.valueOf(torneo.getEquipos().get(idEquipo).getJugadores().size() + 1);
            Jugador jugador = jugadorService.crearJugador(idJugador, txtNombreJugador.getText(), Integer.parseInt(txtNumeroJugador.getText()), txtDireccionJugador.getText(), txtTelefonoJugador.getText());

            torneo.getEquipos().get(idEquipo).setJugador(jugador);
            javax.swing.JOptionPane.showMessageDialog(this, "datos guardados");
            txtNumeroJugador.setText("Ingrese el número con el que jugará");
            txtNombreJugador.setText("Ingrese el nombre del jugador");
            txtTelefonoJugador.setText("Ingrese el teléfono del jugador");
            txtDireccionJugador.setText("Ingrese la dirección del jugador");

            txtNumeroJugador.setForeground(Color.gray);
            txtNombreJugador.setForeground(Color.gray);
            txtTelefonoJugador.setForeground(Color.gray);
            txtDireccionJugador.setForeground(Color.gray);

            jTabbedPane1.setSelectedIndex(3);
            jugadorService.mostrarJugadores(torneo.getEquipos().get(idEquipo).getJugadores(), modelTabla, idEquipo);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "rellene los campos correctamente");
        }

    }//GEN-LAST:event_btnContinuarActionPerformed

    private void txtNumeroJugadorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumeroJugadorMousePressed
        if (txtNumeroJugador.getText().equals("Ingrese el número con el que jugará")) {

            txtNumeroJugador.setText("");
            txtNumeroJugador.setForeground(Color.black);

        }

        if (txtNombreJugador.getText().isEmpty()) {

            txtNombreJugador.setText("Ingrese el nombre del jugador");
            txtTelefonoJugador.setText("Ingrese el teléfono del jugador");
            txtDireccionJugador.setText("Ingrese la dirección del jugador");
            txtNombreJugador.setForeground(Color.gray);

        }

        if (txtDireccionJugador.getText().isEmpty()) {

            txtDireccionJugador.setText("Ingrese la dirección del jugador");
            txtDireccionJugador.setForeground(Color.gray);

        }

        if (txtTelefonoJugador.getText().isEmpty()) {

            txtTelefonoJugador.setText("Ingrese el teléfono del jugador");
            txtTelefonoJugador.setForeground(Color.gray);

        }
    }//GEN-LAST:event_txtNumeroJugadorMousePressed

    private void txtNumeroJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroJugadorActionPerformed

    private void txtTelefonoJugadorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoJugadorMousePressed
        if (txtTelefonoJugador.getText().equals("Ingrese el teléfono del jugador")) {

            txtTelefonoJugador.setText("");
            txtTelefonoJugador.setForeground(Color.black);

        }

        if (txtNombreJugador.getText().isEmpty()) {

            txtNombreJugador.setText("Ingrese el nombre del jugador");
            txtNombreJugador.setForeground(Color.gray);

        }

        if (txtDireccionJugador.getText().isEmpty()) {

            txtDireccionJugador.setText("Ingrese la dirección del jugador");
            txtDireccionJugador.setForeground(Color.gray);

        }

        if (txtNumeroJugador.getText().isEmpty()) {

            txtNumeroJugador.setText("Ingrese el número con el que jugará");
            txtNumeroJugador.setForeground(Color.gray);

        }
    }//GEN-LAST:event_txtTelefonoJugadorMousePressed

    private void txtTelefonoJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoJugadorActionPerformed

    private void txtDireccionJugadorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDireccionJugadorMousePressed

        if (txtDireccionJugador.getText().equals("Ingrese la dirección del jugador")) {

            txtDireccionJugador.setText("");
            txtDireccionJugador.setForeground(Color.black);

        }

        if (txtNombreJugador.getText().isEmpty()) {

            txtNombreJugador.setText("Ingrese el nombre del jugador");
            txtNombreJugador.setForeground(Color.gray);

        }

        if (txtTelefonoJugador.getText().isEmpty()) {

            txtTelefonoJugador.setText("Ingrese el teléfono del jugador");
            txtTelefonoJugador.setForeground(Color.gray);

        }

        if (txtNumeroJugador.getText().isEmpty()) {

            txtNumeroJugador.setText("Ingrese el número con el que jugará");
            txtNumeroJugador.setForeground(Color.gray);

        }

    }//GEN-LAST:event_txtDireccionJugadorMousePressed

    private void txtDireccionJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionJugadorActionPerformed

    private void txtNombreJugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreJugadorMouseClicked

    }//GEN-LAST:event_txtNombreJugadorMouseClicked

    private void txtNombreJugadorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreJugadorMousePressed

        if (txtNombreJugador.getText().equals("Ingrese el nombre del jugador")) {

            txtNombreJugador.setText("");
            txtNombreJugador.setForeground(Color.black);

        }

        if (txtDireccionJugador.getText().isEmpty()) {

            txtDireccionJugador.setText("Ingrese la dirección del jugador");
            txtDireccionJugador.setForeground(Color.gray);

        }

        if (txtTelefonoJugador.getText().isEmpty()) {

            txtTelefonoJugador.setText("Ingrese el teléfono del jugador");
            txtTelefonoJugador.setForeground(Color.gray);

        }

        if (txtNumeroJugador.getText().isEmpty()) {

            txtNumeroJugador.setText("Ingrese el número con el que jugará");
            txtNumeroJugador.setForeground(Color.gray);

        }

    }//GEN-LAST:event_txtNombreJugadorMousePressed

    private void txtNombreJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreJugadorActionPerformed

    private void txtLogoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLogoMousePressed
        JFileChooser selectImage = new JFileChooser();
        String ruta;
        FileNameExtensionFilter filtroBusqueda = new FileNameExtensionFilter("JPG, PNG & GIG", "jpg", "png", "gif");
        selectImage.setFileFilter(filtroBusqueda);

        int opcionSeleccionada = selectImage.showOpenDialog(this);

        if (opcionSeleccionada == JFileChooser.APPROVE_OPTION) {

            ruta = selectImage.getSelectedFile().getPath();
            txtLogo.setText(ruta);
            Image imagenSeleccionada = new ImageIcon(ruta).getImage();

            ImageIcon iconoEquipo = new ImageIcon(
                    imagenSeleccionada.getScaledInstance(jLabel10.getWidth(),
                            jLabel10.getHeight(), Image.SCALE_SMOOTH));

            jLabel10.setIcon(iconoEquipo);

        }
    }//GEN-LAST:event_txtLogoMousePressed

    private void txtLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLogoMouseClicked


    }//GEN-LAST:event_txtLogoMouseClicked

    private void txtLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLogoActionPerformed

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        String ruta = "..\\Torneo\\src\\images\\teamLogo.png";
        txtLogo.setText(ruta);
        Image imagenSeleccionada = new ImageIcon(ruta).getImage();

        ImageIcon iconoEquipo = new ImageIcon(
                imagenSeleccionada.getScaledInstance(jLabel10.getWidth(),
                        jLabel10.getHeight(), Image.SCALE_SMOOTH));

        jLabel10.setIcon(iconoEquipo);
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked

        jTabbedPane1.setSelectedIndex(3);
        txtNumeroJugador.setText("Ingrese el número con el que jugará");
        txtNombreJugador.setText("Ingrese el nombre del jugador");
        txtTelefonoJugador.setText("Ingrese el teléfono del jugador");
        txtDireccionJugador.setText("Ingrese la dirección del jugador");

        txtNumeroJugador.setForeground(Color.gray);
        txtNombreJugador.setForeground(Color.gray);
        txtTelefonoJugador.setForeground(Color.gray);
        txtDireccionJugador.setForeground(Color.gray);
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        jTabbedPane1.setSelectedIndex(2);
        txtNombreEquipo.setText("Ingrese el nombre del equipo");
            txtNombreEquipo.setForeground(Color.gray);
            txtLogo.setText("Click aqui para cargar su logo");
            txtNombreEquipo.setForeground(Color.gray);
            jLabel10.setIcon(null);
            jLabel10.updateUI();
    }//GEN-LAST:event_jLabel23MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel background3;
    private javax.swing.JPanel background4;
    private javax.swing.JPanel background6;
    private javax.swing.JLabel backgroundViewPrincipal;
    private javax.swing.JButton btnAgregarJugador;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnContinuar1;
    private javax.swing.JPanel btnDatosEquipo;
    private javax.swing.JPanel btnDatosJugadores;
    private javax.swing.JPanel btnDatosTorneo;
    private javax.swing.JLabel btnExit;
    private javax.swing.JPanel btnInicio;
    private javax.swing.JPanel btnTablaEncuentro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel logo;
    private javax.swing.JTable tablaEquipos;
    private javax.swing.JTable tablaEquipos1;
    private javax.swing.JTable tablaJugadores;
    private javax.swing.JTextField txtCategoria1;
    private javax.swing.JTextField txtDireccionJugador;
    private javax.swing.JTextField txtLogo;
    private javax.swing.JTextField txtNombreEquipo;
    private javax.swing.JTextField txtNombreJugador;
    private javax.swing.JTextField txtNombreTorneo1;
    private javax.swing.JTextField txtNumeroJugador;
    private javax.swing.JTextField txtTelefonoJugador;
    // End of variables declaration//GEN-END:variables
}
